[package]
name = "ws-client"
version = "0.1.0"
authors = ["gerasyov-2427"]

[dependencies]
net2 = "0.2.27"
websocket-reuseaddr = { git = "https://github.com/nthend/rust-websocket.git", branch = "master", default-features = false }